LeftToRight:
  change-interval: 100
  texts:
    - '&b-&7-----------'
    - '&7-&b-&7----------'
    - '&7--&b-&7---------'
    - '&7---&b-&7--------'
    - '&7----&b-&7-------'
    - '&7-----&b-&7------'
    - '&7------&b-&7-----'
    - '&7-------&b-&7----'
    - '&7--------&b-&7---'
    - '&7---------&b-&7--'
    - '&7----------&b-&7-'
    - '&7-----------&b-'
RightToLeft:
  change-interval: 100
  texts:
    - '&b-&7-----------'
    - '&7-&b-&7----------'
    - '&7--&b-&7---------'
    - '&7---&b-&7--------'
    - '&7----&b-&7-------'
    - '&7-----&b-&7------'
    - '&7------&b-&7-----'
    - '&7-------&b-&7----'
    - '&7--------&b-&7---'
    - '&7---------&b-&7--'
    - '&7----------&b-&7-'
    - '&7-----------&b-'
time:
  change-interval: 3000
  texts:
    - '&7Time &b%time%'
    - '&7Date &b%date%'
barcolors:
  change-interval: 1000
  texts:
    - RED
    - BLUE
    - GREEN
    - YELLOW
